services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8082
    networks:
      - react-network
    restart: always
    command: yarn dev --host


networks:
  react-network:
    driver: bridge